### ISSUE TITLE
How can I install this theme locally on ReadTheDocs ?

### ISSUE THREAD

**Issue by OguzErtanAyanlarW** [bashtage/sphinx-material#24]
Hello, I am trying to install this theme locally on ReadTheDocs (Sphinx Engine). I cloned the git repository, ran the setup.py script and copied the generated sphinx-material directory to my docs/_theme folder and set the theme path on my conf.py but I get following error:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 324, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/builders/html.py", line 329, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/builders/html.py", line 375, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invstr-invstr-doc-test/envs/latest/lib/python3.7/site-packages/sphinx/theming.py", line 286, in create
    '(missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_material' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_material' found (missing theme.conf?)
```

Thanks in advance, really nice theme.

**Comment by OguzErtanAyanlarW** [comment]
To clarify my question, I dont want to install the theme by forking / using the github URL on requirements.txt.

**Comment by bashtage** [comment]
Just add sphinx-material to requirements.txt and it will get the latest version from PyPI.  Does this not work?

**Comment by OguzErtanAyanlarW** [comment]
It works, but I am trying to install a modified version of this theme and I dont want to do this by forking it, modifying it, and then adding my forked github URL. I want to copy the theme files locally to my docs/_themes folder and doing the required modifications locally.

**Comment by bashtage** [comment]
I don't know anything about this.  You should try asking on the sphinx google group. 

Alternatively, you can publish your project to PyPI with a different name,e.g. oguz-rtd-theme, and then install from PyPI.

You also could *probably* install from withing conf.py using subprocess before you import the theme, and then import it which will then be available. Probably not a good idea. 

I think this use outside of the scope of what I can provide in this project.

**Comment by bashtage** [comment]
Oh, and depending on how you are modifiying it, (*I think*) you can just place the modifications in the _theme directory and these will override the defaults in sphinx-material.

**Comment by bashtage** [comment]
I'm just closing this since there is nothing for me to do AFAICT.

**Comment by bashtage** [comment]
Reading this page https://www.sphinx-doc.org/en/master/theming.html I think it isn't possible to install the entire theme this way since it requires some Python code to work.

**Comment by bashtage** [comment]
But you should be able to install sphinx-material, and then override any of the templates with your custom ones in the _theme directory.
