### ISSUE TITLE
Version 0.24 fails to install

### ISSUE THREAD

**Issue by mneil** [bashtage/sphinx-material#40]
Python 3.8
Pip 20
```
ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3291xvju/sphinx-material/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3291xvju/sphinx-material/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3291xvju/sphinx-material/pip-egg-info
         cwd: /tmp/pip-install-3291xvju/sphinx-material/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3291xvju/sphinx-material/setup.py", line 5, in <module>
        with open("requirements.txt") as reqs:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The error is fairly straightforward. I've been bitten by this myself personally. I downloaded your tar from pypi and it's missing the requirements.txt file. Your `setup.py` is trying to read that file.

I suggest you delete the requirements.txt and requirements-dev.txt and stick to using only the setup.py so you don't forget these files in the future.

**Comment by mneil** [comment]
Thanks for the quick fix! And thank you for this package, the UI you ported to sphinx has save me a lot of time :)
